Functions to get elements or properties of matrices

In [1]:
import numpy as np

In [5]:
a_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(a_matrix[0])

[[1 2 3]]


In [7]:
print(a_matrix[1, 0])

4


In [8]:
print(a_matrix[2, 1:3])

[[8 9]]


In [9]:
print(a_matrix[2, [1, 2]])

[[8 9]]


In [10]:
print(a_matrix.size)

9


In [11]:
print(a_matrix.shape)

(3, 3)


In [12]:
print(np.amax(a_matrix))
print(np.amin(a_matrix))
print(np.average(a_matrix))

9
1
5.0


In [13]:
print(a_matrix.max())
print(a_matrix.min())
print(a_matrix.mean())

9
1
5.0
